apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: platform-app-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: platform-app.rules
      rules:

        - alert: PlatformAppTargetMissing
          expr: absent(up{job="platform-app-dev", namespace="dev"})
          for: 10s
          labels:
            severity: warning
          annotations:
            summary: "Platform app target missing"
            description: "Prometheus cannot find any scrape target for platform-app-dev"

        - alert: PlatformAppReplicasUnavailable
          expr: kube_deployment_status_replicas_available{namespace="dev", deployment="platform-app-dev"} 
                < kube_deployment_spec_replicas{namespace="dev", deployment="platform-app-dev"}
          for: 10s
          labels:
            severity: critical
          annotations:
            summary: "Platform app replicas unavailable"
            description: "Available replicas are below desired count for platform-app-dev"

        - alert: PlatformAppRestarting
          expr: increase(kube_pod_container_status_restarts_total{namespace="dev", pod=~"platform-app-dev-.*"}[1m]) > 0
          for: 10s
          labels:
            severity: warning
          annotations:
            summary: "Platform app pod restarting"
            description: "Container restart detected in platform-app-dev pods"
